FROM rsalveti/alpine-arm64:edge

RUN apk add --no-cache ca-certificates mosquitto

# Fix initial start failure so we can run the setup script
RUN touch /var/log/mosquitto.log
RUN chown mosquitto:mosquitto /var/log/mosquitto.log
RUN chmod 644 /var/log/mosquitto.log

EXPOSE 1883 8883

COPY start.sh start.sh
RUN chmod +x start.sh
ENTRYPOINT ["/start.sh"]

# Default to dump service log
CMD tail -f /var/log/mosquitto.log
