FROM linarotechnologies/alpine:v3.5-arm64

RUN apk add --no-cache bash bluez

# BT 6lowpan joiner
RUN mkdir -p /etc/bluetooth/6lowpand/
COPY bluetooth_6lowpand.sh /usr/bin/bluetooth_6lowpand
RUN chmod +x /usr/bin/bluetooth_6lowpand

# Default BlueZ main.conf
COPY main.conf /etc/bluetooth/main.conf

COPY start.sh start.sh
RUN chmod +x start.sh
ENTRYPOINT ["/start.sh"]

# Default to dump joiner log
CMD touch /var/log/bluetooth_6lowpand.log && tail -f /var/log/bluetooth_6lowpand.log
